config/routes.rb
Rails.application.routes.draw do

  get 'hugs/new'
  get 'donationsmanager/menu'
  get 'donationsmanager/thanks'
  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'app#home'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :images, except: :show
    resources :accounts, except: :show
    resources :beverages, only: [:new, :create]
    resources :hugs, only: [:new, :create]
  end

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :profile
  has_one :donation, as: :donable
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donable, polymorphic: true
end

app/models/hug.rb
class Hug < ApplicationRecord
  belongs_to :profile
  has_one :donation, as: :donable
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :profile
  has_one_attached :photo

  scope :public_ones, -> { where(public: true) }

  scope :public_ones_by_profile, -> (profileID) {
    public_ones.where("profile_id = ?", profileID)
  }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :accounts
  has_many :images
  has_many :beverages
  has_many :hugs


  def public_images
    self.images.select { |i| i.public == true }
  end

  def sort_multipliers(params)
    # abort params.inspect
    p = params.select{ |k,v| ["m1", "m2", "m3", "m4"].include? k }
    a = p.to_unsafe_h.map{ |k, v| v.to_i }.sort!
    # abort a.inspect
  end

  def set_donations
    @donations = [];
    @donations << self.beverages
    @donations << self.hugs
    @donations.flatten!
    @donations = @donations.sort_by &:created_at
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_account, only: [:edit, :update, :destroy]

  before_action :check_current_user, only: [:index, :new]

  def index
    @accounts = @profile.accounts
  end

  def new
    @account = Account.new
  end

  def create
    @account = @profile.accounts.build(account_params)
    if @account.save
      redirect_to profile_accounts_path(@profile), notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @profile = @account.profile.id
    if @account.update(account_params)
      redirect_to profile_accounts_path(@profile), notice: 'Your info was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @account.profile.id
    @account.destroy
    redirect_to profile_accounts_path(@profile), notice: 'Info was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_account
    @account = Account.find(params[:id])
  end

  def check_current_user
    if current_user.id != @profile.id
      redirect_to root_path
    end
  end

  def account_params
    params.require(:account).permit(:bank, :kind, :account_number, :email, :cedula, :paypal, :emailpaypal)
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
  end
end

app/controllers/hugs_controller.rb
class HugsController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
    @hug = Hug.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @hug = @profile.hugs.build({duration: params[:hug][:duration]})
    if @hug.save
      @hug.build_donation({
        occupation: params[:hug][:occupation],
        message: params[:hug][:message],
        contributor: params[:hug][:contributor],
      }).save
      redirect_to donationsmanager_thanks_path(@profile), notice: 'Thank you for your donation!'
    else
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_image, only: [:edit, :update, :destroy]

  before_action :check_current_user, only: [:index, :new]

  def index
    @images = @profile.images
  end

  def new
    @image = Image.new
  end

  def create
    @image = @profile.images.build(image_params)
    if @image.save
      redirect_to profile_images_path(@profile), notice: 'image was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    @profile = @image.profile.id
    if @image.update(image_params)
      redirect_to profile_images_path(@profile), notice: 'Your info was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @image.profile.id
    @image.destroy
    redirect_to profile_images_path(@profile), notice: 'Info was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_image
    @image = Image.find(params[:id])
  end

  def check_current_user
    if current_user.id != @profile.id
      redirect_to root_path
    end
  end

  def image_params
    params.require(:image).permit(:subtitle, :public, :photo)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/helpers/hugs_helper.rb
module HugsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/app/home.html.haml
.home-container
  .row.header
    .col-sm-9.button-logo
      =link_to image_tag("logo_button.svg"), root_path

    .col-sm-3.button-session
      -if current_user
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      -else
        = link_to 'Sign  in', new_user_session_path
      %hr.pink-line


  .home-hero
    =image_tag("coffees.svg", :alt => "coffee")

    %h2 Un café  es un abrazo atrapado en una taza


    %p Recibe aprecio y gratitud mediante donaciones online

    .home-button-profile
      -unless current_user
        = link_to 'Crear mi perfil', new_user_registration_path
      -else
        =link_to 'Ir a mi perfil', edit_profile_path(current_user.profile)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AbrazosCafeApp
    = csrf_meta_tags
    = csp_meta_tag
    %link{:href => "https://fonts.googleapis.com/css?family=Happy+Monkey", :rel => "stylesheet"}
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,300i,400,700i", :rel => "stylesheet"}/


    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body

    -# %p.notice
    -#   =notice
    -# %p.alert
    -#   =alert

    = yield

app/views/shared/_admin_nav_side.html.haml
- @images_bool =  current_page?( new_profile_image_path(current_user.profile) ) || current_page?( profile_images_path(current_user.profile) )

- @accounts_bool = current_page?( new_profile_account_path(current_user.profile) ) || current_page?( profile_accounts_path(current_user.profile) )


.icono-nav
  - if current_page?(edit_profile_path(current_user.profile))
    =image_tag "perfilpink.svg", class: 'icon-svg'
    =link_to 'Perfil', edit_profile_path(current_user.profile), id: 'pink-icon'
  - else
    =image_tag "perfil.svg", class: 'icon-svg'
    =link_to 'Perfil', edit_profile_path(current_user.profile)

.icono-nav
  -begin
    -if @images_bool
      =image_tag "perfilpink.svg",  class: 'icon-svg'
      =link_to 'Imágenes', profile_images_path(current_user.profile), id: 'pink-icon'
    -elsif current_page?(edit_image_path)
      =image_tag "perfilpink.svg",  class: 'icon-svg'
      =link_to 'Imágenes', profile_images_path(current_user.profile), id: 'pink-icon'
    -else
      =image_tag "perfil.svg",  class: 'icon-svg'
      =link_to 'Imágenes', profile_images_path(current_user.profile)
  -rescue
    =image_tag "perfil.svg",  class: 'icon-svg'
    =link_to 'Imágenes', profile_images_path(current_user.profile)


.icono-nav
  -begin
    -if @accounts_bool
      =image_tag "cuentaspink.svg",  class: 'icon-svg'
      =link_to 'Cuentas', profile_accounts_path(current_user.profile), id: 'pink-icon'
    -elsif current_page?(edit_account_path)
      =image_tag "cuentaspink.svg",  class: 'icon-svg'
      =link_to 'Cuentas', profile_accounts_path(current_user.profile), id: 'pink-icon'
    -else
      =image_tag "cuentas.svg",  class: 'icon-svg'
      =link_to 'Cuentas', profile_accounts_path(current_user.profile)
  -rescue
    =image_tag "cuentas.svg",  class: 'icon-svg'
    =link_to 'Cuentas', profile_accounts_path(current_user.profile)

app/views/shared/_admin_nav_top.html.haml
-# .col-sm-2.col-xs-9.nav-logo
-#   =link_to image_tag('logo_button.svg'), root_path

-# .col-sm-8.col-xs-1.nav-search
-#   .barra
-# .col-sm-2.col-xs.2.nav-avatar
-#   - begin
-#     =image_tag(current_user.profile.avatar)
-#   - rescue
-#     =link_to image_tag("profile.png")
-#   =link_to current_user.profile.fullname, profile_path(current_user.profile), class: 'fullname-font'


.row.px-0
  .col-sm-2.col-xs-9.nav-logo
    =link_to image_tag('logo_button.svg'), root_path

  .col-sm-10.pt-0.px-0
    .navbartop
      .nav-search
        .barra
      .nav-avatar
        - begin
          =image_tag(current_user.profile.avatar)
        - rescue
          =link_to image_tag("profile.png")
        =link_to current_user.profile.fullname, profile_path(current_user.profile), class: 'fullname-font'

app/views/shared/_public_nav.html.haml
.shared-public-nav-container
  .item-1.circled-avatar
    - begin
      =link_to image_tag(@profile.avatar), profile_path(@profile)
    - rescue
      =link_to image_tag("profile.png"), profile_path(@profile)
  .item-2.datos-nav
    .datosnavwrapper
      =link_to @profile.fullname, profile_path(@profile)
      %span= @profile.occupation
  .item-1.buttonroot
    =link_to image_tag("logo_button.svg"), root_path

app/views/shared/_sessions_nav.html.haml
%p THIS IS THE LAYOUTS NAVIGATION : ONLY SESSIONS HERE
-if current_user
  = link_to 'Sign out', destroy_user_session_path, method: :delete
-else
  = link_to 'Sign in', new_user_session_path
  = link_to 'Sign up', new_user_registration_path
%hr