config/routes.rb
Rails.application.routes.draw do

  get 'hugs/new'
  get 'donationsmanager/menu'
  get 'donationsmanager/thanks'
  devise_for :users, controllers: { registrations: 'registrations'}
  root to: 'app#home'

  resources :profiles, only: [:show, :edit, :update], shallow: true do
    resources :images, except: :show
    resources :accounts, except: :show
    resources :beverages, only: [:new, :create]
    resources :hugs, only: [:new, :create]
  end

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage.rb
class Beverage < ApplicationRecord
  belongs_to :profile
  has_one :donation, as: :donable
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :donable, polymorphic: true
end

app/models/hug.rb
class Hug < ApplicationRecord
  belongs_to :profile
  has_one :donation, as: :donable
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :profile
  has_one_attached :photo

  scope :public_ones, -> { where(public: true) }

  scope :public_ones_by_profile, -> (profileID) {
    public_ones.where("profile_id = ?", profileID)
  }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar
  has_many :accounts
  has_many :images
  has_many :beverages
  has_many :hugs


  def public_images
    self.images.select { |i| i.public == true }
  end

  def sort_multipliers(params)
    # abort params.inspect
    p = params.select{ |k,v| ["m1", "m2", "m3", "m4"].include? k }
    a = p.to_unsafe_h.map{ |k, v| v.to_i }.sort!
    # abort a.inspect
  end

  def set_donations
    @donations = [];
    @donations << self.beverages
    @donations << self.hugs
    @donations.flatten!
    @donations = @donations.sort_by &:created_at
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_account, only: [:edit, :update, :destroy]

  before_action :check_current_user, only: [:index, :new]

  def index
    @accounts = @profile.accounts
  end

  def new
    @account = Account.new
  end

  def create
    @account = @profile.accounts.build(account_params)
    if @account.save
      redirect_to profile_accounts_path(@profile), notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @profile = @account.profile.id
    if @account.update(account_params)
      redirect_to profile_accounts_path(@profile), notice: 'Your info was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @account.profile.id
    @account.destroy
    redirect_to profile_accounts_path(@profile), notice: 'Info was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_account
    @account = Account.find(params[:id])
  end

  def check_current_user
    if current_user.id != @profile.id
      redirect_to root_path
    end
  end

  def account_params
    params.require(:account).permit(:bank, :kind, :account_number, :email, :cedula, :paypal, :emailpaypal)
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
  end
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
    @beverage = Beverage.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @beverage = @profile.beverages.build({quantity: params[:beverage][:quantity]})
    if @beverage.save
      @beverage.build_donation({
        occupation: params[:beverage][:occupation],
        message: params[:beverage][:message],
        contributor: params[:beverage][:contributor],
      }).save
      redirect_to donationsmanager_thanks_path(@profile), notice: 'Thank you for your donation!'
    else
      render :new
    end
  end
end

app/controllers/hugs_controller.rb
class HugsController < ApplicationController
  def new
    @profile = Profile.find(params[:profile_id])
    @hug = Hug.new
  end

  def create
    @profile = Profile.find(params[:profile_id])
    @hug = @profile.hugs.build({duration: params[:hug][:duration]})
    if @hug.save
      @hug.build_donation({
        occupation: params[:hug][:occupation],
        message: params[:hug][:message],
        contributor: params[:hug][:contributor],
      }).save
      redirect_to donationsmanager_thanks_path(@profile), notice: 'Thank you for your donation!'
    else
      render :new
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:index, :new, :create]
  before_action :set_image, only: [:edit, :update, :destroy]

  before_action :check_current_user, only: [:index, :new]

  def index
    @images = @profile.images
  end

  def new
    @image = Image.new
  end

  def create
    @image = @profile.images.build(image_params)
    if @image.save
      redirect_to profile_images_path(@profile), notice: 'image was successfully created.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    @profile = @image.profile.id
    if @image.update(image_params)
      redirect_to profile_images_path(@profile), notice: 'Your info was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @profile = @image.profile.id
    @image.destroy
    redirect_to profile_images_path(@profile), notice: 'Info was successfully destroyed.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:profile_id])
  end

  def set_image
    @image = Image.find(params[:id])
  end

  def check_current_user
    if current_user.id != @profile.id
      redirect_to root_path
    end
  end

  def image_params
    params.require(:image).permit(:subtitle, :public, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_profile, only: [:edit, :update, :show]
  before_action :check_current_user, only: [:edit, :update]

  def edit
  end

  def update
    if @profile.update(profile_params)
      @multipliers = @profile.sort_multipliers( profile_params )
      @profile.update({
        m1: @multipliers[0],
        m2: @multipliers[1],
        m3: @multipliers[2],
        m4: @multipliers[3]
      })
      redirect_to edit_profile_path(@profile.id), notice: 'Your info was successfully edited'
    else
      render :edit
    end
  end

  def show
    @publicImages = Image.public_ones_by_profile(@profile.id)
    # abort @publicImages[0].inspect
    @donations = @profile.set_donations
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def check_current_user
    if current_user.id != @profile.id
      redirect_to root_path
    end
  end

  def profile_params
    params.require(:profile).permit(:fullname, :bio, :occupation, :amount, :currency, :m1, :m2, :m3, :m4, :avatar)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/helpers/donationsmanager_helper.rb
module DonationsmanagerHelper
end

app/helpers/hugs_helper.rb
module HugsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/accounts/edit.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.edit-account.px-5

      .title.pt-5.pl-2
        .subtitle-font
          =link_to image_tag("arrow.png") + " Listado de Cuentas", profile_accounts_path(current_user.profile)
        .admin-title-font
          %h1 Editar Cuenta
          %hr

      = form_with(model: @account, local: true) do |form|
        - if @account.errors.any?
          #error_explanation
            %h2
              = pluralize(@account.errors.count, "error")
              prohibited this profile from being saved:
            %ul
              - @account.errors.full_messages.each do |message|
                %li= message
        .row



          .col-4.instructions-1
            .subtitle-font
              %p.info-a Datos de la cuenta
            .form-font
              %p.info-b Edite los datos de la cuenta que se mostrarán en su perfil público


          .col-8
            .optionscontainer
              .optionswrapper
                #bankedit
                  %span Bank
                #paypaledit
                  %span Paypal
            .account-form-edit
              .banksection
                .field.form-group
                = form.label :bank, 'Banco', class: 'form-font'
                = form.text_field :bank, class: 'form-control'
                .field.form-group
                = form.label :kind, 'Tipo de cuenta', class: 'form-font'
                = form.text_field :kind, class: 'form-control'
                .field.form-group
                = form.label :account_number, 'Número de cuenta', class: 'form-font'
                = form.text_field :account_number, class: 'form-control'
                .field.form-group
                = form.label :email, 'Email', class: 'form-font'
                = form.text_field :email, class: 'form-control'
                .field.form-group
                = form.label :cedula, 'RIF o cédula ', class: 'form-font'
                = form.text_field :cedula, class: 'form-control'

              .paypalsection.d-none
                .field.form-group
                = form.label :paypal, 'Paypal', class: 'form-font'
                = form.text_field :paypal, class: 'form-control'
                .field.form-group
                = form.label :emailpaypal, 'Email', class: 'form-font'
                = form.text_field :emailpaypal, class: 'form-control'
        %hr
        .footer
          = form.submit 'Guardar', class: 'btn pink-button form-font'

app/views/accounts/index.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.index-account.px-5


      .title.pt-5.pl-2
        .admin-title-font
          %h1 Listado de cuentas
        .form-font
          = link_to 'Agregar', new_profile_account_path(@profile), class: 'pink-button form-font'
        %hr

      .accounts-table.mt-5
        %table.table.carusel-index-font
          .table-encabezado
            %p Cuentas
            %hr
          %thead
            %tr
              %th.py-4 Banco
              %th.py-4 Tipo de cuenta
              %th.py-4 Número de cuenta
              %th.py-4 Email
              %th{colspan: "3"}
          %tbody
            - @accounts.each do |account|
              %tr
                %td.py-4
                  -if account.bank != ''
                    %p=account.bank
                  -elsif account.paypal != ''
                    %p=account.paypal
                %td.py-4
                  %p= account.kind
                %td.py-4
                  %p= account.account_number
                %td.py-4
                  -if account.email != ''
                    %p= account.email
                  -elsif account.emailpaypal != ''
                    %p= account.emailpaypal
                %td.pb-4.icons-actions
                  =image_tag "dots.png", class: 'dots'
                  .hideme
                    .element
                      = link_to 'Editar', edit_account_path( account )
                    .element.eliminar
                      =image_tag('equis.png')
                      = link_to 'Eliminar', account, method: :delete, data: { confirm: 'Are you sure?' }

app/views/accounts/new.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.new-account.px-5

      .title.pt-5.pl-2
        .subtitle-font
          =link_to image_tag("arrow.png") + " Listado de Cuentas", profile_accounts_path(current_user.profile)
        .admin-title-font
          %h1 Agregar Cuenta
          %hr

      = form_with(model: [@profile, @account], local: true) do |form|
        - if @account.errors.any?
          #error_explanation
            %h2
              = pluralize(@account.errors.count, "error")
              prohibited this profile from being saved:
            %ul
              - @account.errors.full_messages.each do |message|
                %li= message
        .row
          .col-4.instructions-1
            .subtitle-font
              %p.info-a Datos de la cuenta
            .form-font
              %p.info-b Agregue los datos de la cuenta que se mostrarán en su perfil público

          .col-8

            .optionscontainer
              .optionswrapper
                #bank
                  %span Bank
                #paypal
                  %span Paypal
            .account-form-new
              .banksection
                .field.form-group
                = form.label :bank, 'Banco', class: 'form-font'
                = form.text_field :bank, class: 'form-control'
                .field.form-group
                = form.label :kind, 'Tipo de cuenta', class: 'form-font'
                = form.text_field :kind, class: 'form-control'
                .field.form-group
                = form.label :account_number, 'Número de cuenta', class: 'form-font'
                = form.text_field :account_number, class: 'form-control'
                .field.form-group
                = form.label :email, 'Email', class: 'form-font'
                = form.text_field :email, class: 'form-control'
                .field.form-group
                = form.label :cedula, 'RIF o cédula ', class: 'form-font'
                = form.text_field :cedula, class: 'form-control'


              .paypalsection.d-none
                .field.form-group
                = form.label :paypal, 'Paypal', class: 'form-font'
                = form.text_field :paypal, class: 'form-control'
                .field.form-group
                = form.label :emailpaypal, 'Email', class: 'form-font'
                = form.text_field :emailpaypal, class: 'form-control'

        %hr

        .footer
          = form.submit 'Guardar', class: 'btn pink-button form-font'

app/views/beverages/new.html.haml
=render 'shared/public_nav'
.coffee-new-container

  .bevereages-new-hero-header
    =link_to '< Atrás', :back
    %p ¿Cuántos cafes?


  = form_with(model: [@profile, @beverage], local: true, id: 'ffff') do |form|
    - if @beverage.errors.any?
      #error_explanation
        %h2
          = pluralize(@beverage.errors.count, "error")
          prohibited this profile from being saved:
        %ul
          - @beverage.errors.full_messages.each do |message|
            %li= message

    .form-container-no-button

      .part-1.form-card

        .side-a
          =image_tag("coffe.svg")
          %br
          %span#amount= @profile.amount.to_s + " " + @profile.currency

        .side-middle
          %span X

        .side-b
          .radio-circle
            = form.radio_button :quantity, @profile.m1, id: 'radiobutton1'
            %span= @profile.m1
          .radio-circle
            = form.radio_button :quantity, @profile.m2, id: 'radiobutton2'
            %span= @profile.m2
          .radio-circle
            = form.radio_button :quantity, @profile.m3, id: 'radiobutton3'
            %span= @profile.m3
          .radio-circle
            = form.radio_button :quantity, @profile.m4, id: 'radiobutton4'
            %span= @profile.m4
          %br
          %span.total Total:
          %span#total.total 0
          %span.total= @profile.currency


      #accounts-info.form-card
        %p.datos-de=  "Datos de  " + @profile.fullname.split[0]

        -@profile.accounts.each do |account|
          -if account.bank != ''
            %p
              %span.accounts-info-title Entidad:
              =account.bank

          -if account.paypal != ''
            %p
              %span.accounts-info-title Entidad:
              =account.paypal

          -if account.email != ''
            %p
              %span.accounts-info-title Email:
              =account.email

          -if account.emailpaypal != ''
            %p
              %span.accounts-info-title Email:
              =account.emailpaypal

          -if account.account_number != ''
            %p
              %span.accounts-info-title Nro de cuenta:
              =account.account_number

          -if account.kind != ''
            %p
              %span.accounts-info-title Tipo de cuenta:
              =account.kind

          -if account.cedula != ''
            %p
              %span.accounts-info-title RIF o cédula :
              =account.cedula

          %br
          - if @profile.accounts.last != account
            %hr
          %br



      #part-2.form-card
        %p.tus-datos Tus datos

        = form.label :contributor, 'Nombre'
        = form.text_field :contributor, class: 'form-control'

        = form.label :occupation, 'Ocupación'
        = form.text_field :occupation, class: 'form-control'

        = form.label :message, 'Mensaje de agradecimiento'
        = form.text_area :message, class: 'form-control ', maxlength: '150'




    .actions
      = form.submit '¡Listo! Notificar a ' + @profile.fullname.split[0], class: 'btn beverages-submit'

app/views/hugs/new.html.haml
=render 'shared/public_nav'
.hug-new-container

  .header
    =link_to '< Atrás', :back
    %p.hide-me Presiona el botón para abrazar

  = form_with(model: [@profile, @hug], local: true) do |form|
    - if @hug.errors.any?
      #error_explanation
        %h2
          = pluralize(@hug.errors.count, "error")
          prohibited this profile from being saved:
        %ul
          - @hug.errors.full_messages.each do |message|
            %li= message

    .form-container-no-button
      .hug-section
        .hug-touch
          =image_tag "hug.svg", class: 'svghug'
          .mini-circle-1.mini-circles
          .mini-circle-2.mini-circles
          .mini-circle-3.mini-circles
          .mini-circle-4.mini-circles
          .mini-circle-5.mini-circles
          .mini-circle-6.mini-circles
          .mini-circle-7.mini-circles
          .mini-circle-8.mini-circles
        = form.text_field :duration, class: 'form-control inputseconds d-none'
        %p.timer-counter
          %span Abrazo de
          %span.seconds 0
          %span.miliseconds .00
          %span segundos
        %span.instructions-hug Mientras más tiempo lo presiones, mayor será el abrazo



      .form-section.d-none
        %p.header-b
          %strong
            %span Enviando un abrazo de
            %span.seconds 0
            %span.miliseconds .00
            %span seg
        .form-section-card
          %p Tus datos

          = form.label :contributor, 'Nombre'
          = form.text_field :contributor, class: 'form-control'

          = form.label :occupation, 'Ocupación'
          = form.text_field :occupation, class: 'form-control'

          = form.label :message, 'Mensaje de agradecimiento'
          = form.text_area :message, class: 'form-control', maxlength: '150'

    .actions.hugs-submit-container.d-none
      = form.submit '¡Listo! Notificar a ' + @profile.fullname.split[0], class: 'btn hugs-submit'

  #testme.hugs-next.btn
    Siguiente

app/views/images/edit.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.main-content-images-edit.px-5

      .title.pt-5.pl-2
        .subtitle-font
          =link_to image_tag("arrow.png") + " Listado de Imagenes", profile_images_path(current_user.profile)
        .admin-title-font
          %h1 Editar Imagen
          %hr

      .row



        .col-sm-5.instructions-1
          .subtitle-font
            %p.info-a Imagen actual del carousel
          .form-font
            %p.info-b Editar imagen que se mostrará en el carousel del perfil público
        .col-sm-7.current-image
          - begin
            =image_tag(@image.photo)
          - rescue
            %p no image yet
      %hr.lonehr


      = form_with(model: @image, local: true) do |form|
        - if @image.errors.any?
          #error_explanation
            %h2
              = pluralize(@image.errors.count, "error")
              prohibited this profile from being saved:
            %ul
              - @image.errors.full_messages.each do |message|
                %li= message


        .row
          .col-sm-5.instructions-1
            .subtitle-font
              %p.info-a Imagen del carousel
            .form-font
              %p.info-b Editar imagen que se mostrará en el carousel del perfil público

          .col-sm-7
            .images-card.py-5.form-font
              %span.span-load-image Cargar Imagen
              = form.file_field :photo, class: 'form-control dropify '
        %hr

        .row.mt-5
          .col-sm-5.instructions-2
            .subtitle-font
              %p.info-a Datos de la imagen
            .form-font
              %p.info-b Parámetros de la publicación y leyenda de la imagen a mostrarse en el carousel
          .col-sm-7
            .images-card-3.subtitle-font
              = form.label :subtitle, 'Subtítulo'
              = form.text_field :subtitle, class: 'form-control'
              .checkbox.form-font
                .styled-checkbox
                  = form.check_box :public, class: 'box-input'
                = form.label :public, 'Mostrar esta imagen en el perfil público'
        %hr

        .footer
          = form.submit 'Guardar', class: 'btn images-edit-save form-font'

app/views/images/index.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.main-content-images-index.px-5


      .title.pt-5.pl-2
        .admin-title-font
          %h1 Carousel de imagenes
        .form-font
          = link_to 'Agregar', new_profile_image_path(@profile)
          %hr


      .images-card.mt-5
        %p Imágenes
        %hr.pink-line

        - @images.each do |image|
          %hr
          .row
            .col-sm-2.py-3.to-the-right
              = image_tag(image.photo)
            .col-sm-7.pt-4.pb-3.subtitle
              %p= image.subtitle
            .col-sm-3.py-3
              .icons-actions
                =image_tag "dots.png", class: 'dots'


                .hideme
                  -# =image_tag "bubble.svg", class: 'bubble'
                  .element
                    = link_to 'Editar', edit_image_path( image ), class: 'link1'
                  .element.eliminar
                    =image_tag('equis.png')
                    = link_to 'Eliminar', image, class: 'link2', method: :delete, data: { confirm: 'Are you sure?' }

app/views/images/new.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.main-content-images-new.px-5

      .title.pt-5.pl-2
        .subtitle-font
          =link_to image_tag("arrow.png") + " Listado de Imagenes", profile_images_path(@profile)
        .admin-title-font
          %h1 Agregar Imagen
          %hr

      = form_with(model: [@profile, @image], local: true) do |form|
        - if @image.errors.any?
          #error_explanation
            %h2
              = pluralize(@image.errors.count, "error")
              prohibited this profile from being saved:
            %ul
              - @image.errors.full_messages.each do |message|
                %li= message
        .row
          .col-sm-5.instructions-1
            .subtitle-font
              %p.info-a Imagen del carousel
            .form-font
              %p.info-b Agregar imagen que se mostrará en el carousel del perfil público
          .col-sm-7
            .images-card.py-5.form-font
              %span.span-imagen-principal Imagen principal
              %span.span-load-image Cargar Imagen
              = form.file_field :photo, class: ' dropify'


        .row
          .col-sm-5.instructions-2
            .subtitle-font
              %p.info-a Datos de la imagen
            .form-font
              %p.info-b Parámetros de la publicación y leyenda de la imagen a mostrarse en el carousel
          .col-sm-7
            .images-card-2.form-font

              = form.label :subtitle, 'Subtítulo'
              = form.text_field :subtitle, class: 'form-control'
              .checkbox
                .styled-checkbox
                  = form.check_box :public, class: 'box-input'
                = form.label :public, 'Mostrar esta imagen en el perfil público'
        %hr


        .footer
          = form.submit 'Guardar', class: 'btn images-new-save form-font'

app/views/profiles/edit.html.haml
.container-fluid


  =render 'shared/admin_nav_top'

  .row.full-screen
    .col-2.side-bar.pl-4.pt-4
      =render 'shared/admin_nav_side'

    .col-10.main-content-profile-edit.px-5

      .title.pt-5.pl-2.admin-title-font
        %h1 Perfil del usuario
        %hr

      = form_with(model: @profile, local: true) do |form|
        - if @profile.errors.any?
          #error_explanation
            %h2
              = pluralize(@profile.errors.count, "error")
              prohibited this profile from being saved:
            %ul
              - @profile.errors.full_messages.each do |message|
                %li= message
        .row
          .col-sm-7.col-xs-12.p-4
            .profile-edit-form
              .row
                .col-sm-6
                  = form.label :fullname, 'Nombre y Apellido', class: 'form-font'
                  = form.text_field :fullname, class: 'form-control'
                .col-sm-6
                  = form.label :occupation, 'Ocupación o rol', class: 'form-font'
                  = form.text_field :occupation, class: 'form-control'
              .row
                .col-sm-12.pt-5.pb-2
                  = form.label :bio, 'Biografía', class: 'form-font'
                  = form.hidden_field :bio, class: 'form-control', id: 'wys'
                  %trix-editor.trix-editor{ input: 'wys'}
          .col-sm-5.col-xs.12.p-4
            .profile-edit-form
              = form.label :amount, 'Monto de un café', class: 'form-font'
              = form.text_field :amount, class: 'form-control'
              .field.form-group
              = form.label :currency, 'Símbolo de la moneda', class: 'form-font'
              = form.text_field :currency, class: 'form-control'
              .multiplicadores
                %p.form-font Multiplicadores
                .radio-inputs
                  =form.text_field :m1, class: 'form-control form-coffe-numbers', maxlength: '1'
                  =form.text_field :m2, class: 'form-control form-coffe-numbers', maxlength: '1'
                  =form.text_field :m3, class: 'form-control form-coffe-numbers', maxlength: '1'
                  =form.text_field :m4, class: 'form-control form-coffe-numbers', maxlength: '1'
        %hr
        .row.image-section
          .col-sm-5.text-center.pt-5.form-font
            %p Puedes subir tu foto de perfil aquí
          .col-sm-7
            = form.file_field :avatar, class: 'dropify load-area'
        %hr
        .footer
          = form.submit 'Guardar', class: 'btn profile-save form-font'

app/views/profiles/show.html.haml
=render 'shared/public_nav'

.profile-show-container

  .profile-bio
    %p= sanitize @profile.bio


  #carouselControlsImages.carousel.slide{"data-ride" => "carousel"}
    .carousel-inner
      - @publicImages.each do |image|
        .carousel-item.carouselitemimages
          .profile-images
            -begin
              =image_tag(image.photo)
              %span=image.subtitle
            -rescue
              =image_tag("coffe.png")
    %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselControlsImages", :role => "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", :href => "#carouselControlsImages", :role => "button"}
      %span.carousel-control-next-icon{"aria-hidden" => "true"}
      %span.sr-only Next





  #carouselControlsDonations.carousel.slide{"data-ride" => "carousel"}
    .carousel-inner
      -@donations.each do |d|
        .carousel-item.carouselitemdonations
          .profile-donations
            -if d.kind_of?(Beverage)
              =image_tag 'coffe.png',  class: 'donation-coffee'
              #number-circle
                %span#number-quantity= d.quantity
            - elsif d.kind_of?(Hug)
              =image_tag 'heart.png' , class: 'donation-hug'
              -# %p.number-duration= d.duration
            - begin
              %span.name= d.donation.contributor
              %span.occupation= d.donation.occupation
              %p.message= d. donation.message
            - rescue
              %p no message here
    %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselControlsDonations", :role => "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.carousel-control-next{"data-slide" => "next", :href => "#carouselControlsDonations", :role => "button"}
      %span.carousel-control-next-icon{"aria-hidden" => "true"}
      %span.sr-only Next



  .btn.profile-to-menu-button
    -if @profile.fullname != ''
      = link_to 'Dar abrazos o cafés a ' + @profile.fullname.split[0], donationsmanager_menu_path(@profile)
    - else
      %p Este perfil aun esta vacio!